# Generated by Django 3.2.19 on 2023-11-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_auto_20231128_1116'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'items'},
        ),
    ]
